matrix:
  include:
    - language: nix
      script:
        - nix-shell --pure --run "cargo build --all --all-features"
        - nix-shell --pure --run "cargo test --all --all-features"

jobs:
  fast_finish: true

notifications:
  email:
    on_success: never
    on_failure: always

